name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  dotai-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
      - name: Install node-gyp
        run: |
          bun install node-gyp
      - name: Install dependencies
        run: |
          bun install
      - name: Build
        run: |
          bun run build
      - name: Generate
        run: |
          bun run generate
